version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-and-patch:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns: ["*"]
