-- 0020_roleplay.sql — Admin role-play simulations (F8, marathon July 8/9).
-- "Jump in as the employee": the admin picks a cast persona and takes a live interview
-- AS that character, testing the interviewer. roleplay is a voice_test-CLASS kind:
-- fully firewalled from real records (compile skips it, disclosure screening skips it,
-- it never lists as an interview). After the call, an observation debrief (what the
-- interviewer did well / missed, per objective) is generated by the roleplay_debrief
-- agent and stored here — the feedback loop, not client data.

alter table interview_sessions drop constraint if exists interview_sessions_session_kind_check;
alter table interview_sessions add constraint interview_sessions_session_kind_check
  check (session_kind in ('interview', 'context', 'eval', 'people_map', 'demo', 'voice_test', 'roleplay'));

create table if not exists roleplay_debriefs (
  session_id   uuid primary key references interview_sessions(id) on delete cascade,
  persona_key  text not null,
  document     jsonb not null,
  generated_at timestamptz not null default now()
);

insert into agent_configs (agent_name, model, prompt_path) values
  ('roleplay_debrief', 'claude-sonnet-4-6', 'prompts/agents/roleplay-debrief.md')
  on conflict (agent_name) do nothing;
